### 获取用户
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.tannn.trpc.demo.api.UserService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [101]
}

### mock -- 没有做方法过滤，此出测试对象自带的 hashCode toString 方法的调用
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.tannn.trpc.demo.api.UserService",
  "methodSign": "toString",
  "args": []
}
