server:
  port: 8081

logging:
  level:
    root: error
    cn.tannn.trpc: debug
trpc:
  rc:
    name: zk
  api:
#    enabled: false
    context: trpc
  app:
    appid: provider
    version: 0.0.1
    env: dev
    namespace: public
    gray:
      dc: cqs
      gray: false
      unit: A001
