### User 测试返回对象为Bean
GET http://localhost:8088/user/12

### User 测试返回对象为数字
GET http://localhost:8088/user/id


### User 测试返回对象为字符串
GET http://localhost:8088/user/name



### Order 测试返回对象为Bean
GET http://localhost:8088/order/13

### Order 测试返回对象为数字
GET http://localhost:8088/order/404

### Order findId
GET http://localhost:8088/order/id

### Order 测试返回对象为数字
GET http://localhost:8088/order/l/22



### 负载均衡测试
GET http://localhost:8088/loadBalancer/12
