server:
  port: 8088

logging:
  level:
    root: error
    cn.tannn.trpc: debug
trpc:
  scan-packages: cn.tannn.trpc
  rc:
    name: zk
    namespace: trpc
    connect:
      - ip: 127.0.0.1
        port: 20242
    providers: # rc.name=def用
      - 127.0.0.1_8081_trpc
      - 127.0.0.1_8082_trpc
      - 127.0.0.1_8083_trpc
  consumer:
    http:
      timeout: 2000
      retries: 2
    load-balancer: round_ribbon
    filter:
#      - cache
      - local_method
      - context_parameter
    subscribe:
      appid: provider
      version: 0.0.1
      env: dev
      namespace: public
    gray-ratio: 0
    isolate:
      fault-limit: 5
      half-open-enable: true
      delay: 100
