server:
  port: 8088

trpc:
  # 逗号隔开
  providers:
    - 127.0.0.1_8081
    - 127.0.0.1_8082
    - 127.0.0.1_8083
  scan-packages:
    - cn.tannn.trpc.demo.consumer
  registry-center: zk
#  load-balancer: ROUND_RIBBON
