server:
  port: 8088

logging:
  level:
    root: error
    cn.tannn.trpc: debug
trpc:
  scan-packages: cn.tannn.trpc
  rc:
    name: def
    providers:
      - 127.0.0.1_8081_/trpc
      - 127.0.0.1_8082_/trpc
      - 127.0.0.1_8083_/trpc
  consumer:
    http:
      timeout: 2000
      retries: 2
    load-balancer: round_ribbon
    filter:
#      - cache
      - local_method
